# === General settings ===
headless: true                  # Run emulation without displaying the screen
debug: false                    # Show debug information in the console
server: false                   # Server mode for remote control (e.g., using sockets)
load_checkpoint: ""
notes: "[Final analysis 4 cores + 100000 steps + good visit map]"
root_dir: "game&results/Pokemon_red_env/checkpoints"

# === Emulation and environment ===
emulation_speed: 5              # Emulation speed (1 = real time, >1 = faster)
action_freq: 24                 # Apply an action every X frames
init_state: "game&results/Pokemon_red_env/STELLE.state"  # Initial state for reset
gb_path: "game&results/Pokemon_red_env/PokemonRed.gb"    # Path to game ROM file

# === Observation and encoding ===
actions_stack: 3                # Number of previous actions to stack
coords_pad: 18                  # Padding applied to encoded coordinates

# === Rewards and exploration ===
reward_scale: 1                 # Base reward scale
explore_weight: 0.25            # Relative weight of the exploration reward
step_discount: 0.0004

# === Training ===
num_cpu: 4                      # Number of parallel environments (threads)
checkpoint_save_freq: 16384    # Steps between model checkpoints
max_steps: 102400               # Maximum number of steps per iteration
train_steps_batch: 128
bach_size: 64
reward_threshold: -1

# === Logging & sessions ===
print_rewards: false            # Print rewards to console during training
save_video: false               # Save video of episodes
progress_bar: false
save_stats_every: 1

# === WandB (Weights & Biases) ===
use_wandb: false                # Enable tracking with WandB
wandb_project: pokemon-train    # WandB project name


